# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  host: localhost
  adapter: postgresql
  database: fmdev
  username: fmdev
  password: 123

test: &TEST
  host: localhost
  adapter: postgresql
  database: fmtest
  username: fmdev
  password: 123

production:
  host: localhost
  adapter: postgresql
  database: fmprod
  username: fmprod
  password: 123

cucumber:
  <<: *TEST
