# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: sqlite3
  database: db/dev.sqlite3
  pool: 5
  timeout: 5000

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: /var/run/postgresql
  database: fm
  username: fm
  password: test

cucumber:
  <<: *TEST
