require File.dirname(__FILE__) + '/../spec_helper'

class SomeController < ApplicationController
  def index
    @params = params
    render :text => ""
  end
end

describe ApplicationController do
  before(:each) do
    @instance = ApplicationController.new
  end
  
  it "should parse dates inside json params" do
    d = DateTime.new(2010, 4, 25, 13, 44, 12, 0)
    @instance.parse_json_dates('2010-04-25T13:44:12Z').should == DateTime.new(2010, 4, 25, 13, 44, 12, 0).utc
  end
end

describe SomeController do
  describe "parse_date_time" do
    def params_should_hold_date
      assigns[:params]["x"].should == Date.new(2010, 3, 13)
    end

    def params_should_hold_datetime
      assigns[:params]["x"].should == DateTime.new(2010, 3, 13, 15, 30)
    end
    
    it "should parse dates in human style" do
      get :index, :x_parse_date => "13.03.2010"
      params_should_hold_date
    end

    it "should parse datetimes in human style" do
      get :index, :x_parse_datetime => "13.03.2010 15:30"
      params_should_hold_datetime
    end

    it "should parse dates generated by to_s" do
      get :index, :x_parse_date => Date.new(2010, 3, 13).to_s
      params_should_hold_date
    end

    it "should parse datetimes generated by to_s" do
      get :index, :x_parse_datetime => DateTime.new(2010, 3, 13, 15, 30, 0).to_s
      params_should_hold_datetime
    end

    it "should not fail when passed rubbish" do
      get :index, :x_parse_datetime => "fklajdsflkjasdkflflkdsj"
    end
  end
end
